Repository talamortis/OregonCore, pull requests merged in 2020-05, with the labels that each got.

#137 Raid/Scripts: Black Temple Fix Start [Reliquary of Souls]
  src/scripts/Outland/BlackTemple/boss_reliquary_of_souls.cpp
Labels: TBC Raid, need's testing

#140 Move chat commands to the AC/TrinityCore system ( WIP )
  CMakeLists.txt
  cmake/GroupSources.cmake
  sql/updates/world/2020_04_27_updating_commands.sql
  src/game/Chat.cpp
  src/game/Chat.h
  src/game/Language.h
  src/game/Level0.cpp
  src/game/Level1.cpp
  src/game/Level2.cpp
  src/game/Level3.cpp
  src/game/Level4.cpp
  src/game/ScriptLoader.cpp
  src/game/ScriptMgr.cpp
  src/game/ScriptMgr.h
  src/scripts/CMakeLists.txt
  src/scripts/Commands/cs_account.cpp
  src/scripts/Commands/cs_ban.cpp
  src/scripts/Commands/cs_cast.cpp
  src/scripts/Commands/cs_character.cpp
  src/scripts/Commands/cs_cheat.cpp
  src/scripts/Commands/cs_debug.cpp
  src/scripts/Commands/cs_event.cpp
  src/scripts/Commands/cs_gm.cpp
  src/scripts/Commands/cs_go.cpp
  src/scripts/Commands/cs_gobject.cpp
  src/scripts/Commands/cs_group.cpp
  src/scripts/Commands/cs_guild.cpp
  src/scripts/Commands/cs_honor.cpp
  src/scripts/Commands/cs_instance.cpp
  src/scripts/Commands/cs_learn.cpp
  src/scripts/Commands/cs_list.cpp
  src/scripts/Commands/cs_lookup.cpp
  src/scripts/Commands/cs_message.cpp
  src/scripts/Commands/cs_misc.cpp
  src/scripts/Commands/cs_modify.cpp
  src/scripts/Commands/cs_npc.cpp
  src/scripts/Commands/cs_pdump.cpp
  src/scripts/Commands/cs_pet.cpp
  src/scripts/Commands/cs_quest.cpp
  src/scripts/Commands/cs_reload.cpp
  src/scripts/Commands/cs_reset.cpp
  src/scripts/Commands/cs_server.cpp
  src/scripts/Commands/cs_tele.cpp
  src/scripts/Commands/cs_ticket.cpp
  src/scripts/Commands/cs_titles.cpp
  src/scripts/Commands/cs_wp.cpp
Labels: WIP

#136 DB/Quest: Heart of Hakkar
  sql/updates/world/2020_04_18_Heart of Hakkar_quest.sql
Labels: Fixed
